gui:
  theme:
    activeBorderColor:
      - "#f5c2e7"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    selectedRangeBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#f5c2e7"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"

customCommands:
  - key: "G"
    context: "files"
    description: "Generate a commit message with opencommit"
    command: "opencommit"
    subprocess: true
    showOutput: true
    stream: true
