gui:
  theme:
    lightTheme: false
    activeBorderColor:
      - "#a6e3a1" # Green
      - bold
    inactiveBorderColor:
      - "#cdd6f4" # Text
    optionsTextColor:
      - "#89b4fa" # Blue
    selectedLineBgColor:
      - "#313244" # Surface0
    selectedRangeBgColor:
      - "#313244" # Surface0
    cherryPickedCommitBgColor:
      - "#94e2d5" # Teal
    cherryPickedCommitFgColor:
      - "#89b4fa" # Blue
    unstagedChangesColor:
      - red # Red

customCommands:
  - key: "G"
    context: "files"
    description: "Generate a commit message with opencommit"
    command: "opencommit"
    subprocess: true
    showOutput: true
    stream: true
  - key: "O"
    context: "global"
    description: Open the repo in github
    command: |
      url=$(git config --get remote.origin.url)
      https="https://github.com/"
      echo "goturl: ${url}"
      if [[ $url =~ ^git@ ]]; then
        url=${url/git@github.com:/$https}
      elif [[ $url =~ ^https:// ]]; then
        url=${url/.git/}
      else
        echo "Error: Unable to parse Git URL"
        return 1
      fi
      open $url
    subprocess: false
    showOutput: false
    stream: false
