return {}
-- local cmp = require("cmp")
--
-- -- Setup up vim-dadbod
-- cmp.setup.filetype({ "sql" }, {
--   sources = {
--     { name = "vim-dadbod-completion" },
--     { name = "buffer" },
--   },
-- })
--
-- return {
--   "kristijanhusak/vim-dadbod-ui",
--   dependencies = {
--     { "tpope/vim-dadbod", lazy = true },
--     { "kristijanhusak/vim-dadbod-completion", ft = { "sql", "mysql", "plsql" }, lazy = true },
--   },
--   cmd = {
--     "DBUI",
--     "DBUIToggle",
--     "DBUIAddConnection",
--     "DBUIFindBuffer",
--   },
--   init = function()
--     -- Your DBUI configuration
--     vim.g.db_ui_use_nerd_fonts = 1
--   end,
-- }
