theme = "tokyonight"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
bufferline = "multiple"
mouse = false


[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name", "file-encoding", "diagnostics"]
right = ["selections", "position"]
separator = "|"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-signature-help-docs = true
display-inlay-hints = true
display-messages = true

[keys.normal]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
