{ ... }:
{
  imports = [
    ./atuin.nix
    ./bat.nix
    ./bottom.nix
    ./eza.nix
    ./fd.nix
    ./fish.nix
    ./fzf.nix
    ./gh.nix
    ./go.nix
    ./gh-dash.nix
    ./git.nix
    ./helix.nix
    ./k9s.nix
    ./lazydocker.nix
    ./lazygit.nix
    ./nushell.nix
    ./poetry.nix
    ./pyenv.nix
    ./ripgrep.nix
    ./starship.nix
    ./ssh.nix
    ./thefuck.nix
    ./wezterm.nix
    ./yazi.nix
    ./zellij.nix
    ./zsh.nix
    ./zoxide.nix
  ];
}
